# Generated by Django 5.2.4 on 2025-07-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("filter_operations", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bookmanytomany",
            index=models.Index(fields=["genre"], name="many_to_many_genre_idx"),
        ),
        migrations.AddIndex(
            model_name="bookmanytomany",
            index=models.Index(
                fields=["publish_date"], name="many_to_many_publish_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookonetomany",
            index=models.Index(fields=["genre"], name="one_to_many_genre_idx"),
        ),
        migrations.AddIndex(
            model_name="bookonetomany",
            index=models.Index(
                fields=["publish_date"], name="one_to_many_publish_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookonetoone",
            index=models.Index(fields=["genre"], name="one_to_one_genre_idx"),
        ),
        migrations.AddIndex(
            model_name="bookonetoone",
            index=models.Index(
                fields=["publish_date"], name="one_to_one_publish_date_idx"
            ),
        ),
    ]
